version: "3.9"
services:
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      # AMQP protocol port
      - "5672:5672"
      # Management UI
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  gateway:
    container_name: gateway_container
    build:
      context: ./packages/api-gateway
      dockerfile: Dockerfile.dev
    image: chekromlek-monorepo-gateway
    restart: always
    ports:
      - 3000:3000
    env_file: ./packages/api-gateway/configs/.env
    environment:
      - DOCKER_ENV=true # Indicate that it's a Docker environment
      - AUTH_SERVICE_URL=http://auth:3001 # URL for the Auth service
      - USER_SERVICE_URL=http://user-profile:4000 # URL for the User Profile service
      - NOTIFICATION_SERVICE_URL=http://notification:3002 # URL for the Notification service
      - POST_SERVICE_URL=http://post:3005
      - CLIENT_URL=http://localhost:9000
    secrets:
      - jwt_public_key
    volumes:
      - ./packages/api-gateway/src:/app/src

  auth:
    container_name: auth_container
    build:
      context: ./packages/auth
      dockerfile: Dockerfile.dev
    image: chekromlek-monorepo-auth
    restart: always
    ports:
      - 3001:3001
    env_file: ./packages/auth/configs/.env
    environment:
      - DOCKER_ENV=true
    secrets:
      - jwt_private_key
    depends_on:
      - rabbitmq
    volumes:
      - ./packages/auth/src:/app/src

  user-profile:
    container_name: user-profile_container
    build:
      context: ./packages/users
      dockerfile: Dockerfile.dev
    image: chekromlek-monorepo-user-profile
    restart: always
    ports:
      - 4000:4000
    env_file: ./packages/users/configs/.env
    volumes:
      - ./packages/users/src:/app/src

  notification:
    container_name: notification_container
    build:
      context: ./packages/notification
      dockerfile: Dockerfile.dev
    image: chekromlek-monorepo-notification
    restart: always
    ports:
      - 3002:3002
    env_file: ./packages/notification/configs/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - DOCKER_ENV=true # Indicate that it's a Docker environment
      - API_GATEWAY=http://gateway:3000 # URL for the API Gateway service
      - RABBITMQ_ENDPOINT=amqp://myuser:mypassword@rabbitmq:5672
    volumes:
      - ./packages/notification/src:/app/src

  post:
    container_name: post_container
    build:
      context: ./packages/post # Path to the post service's code
      dockerfile: Dockerfile.dev # Use the Dockerfile created for the "post" service
    restart: always
    ports:
      - 3005:3005
    env_file: ./packages/post/configs/.env
    volumes:
      - ./packages/post/src:/app/src

secrets:
  jwt_public_key:
    file: ./packages/api-gateway/configs/public_key.pem
    
  jwt_private_key:
    file: ./packages/auth/configs/private_key.pem # Path to JWT private key file
